name: Node.js Package

on:
  push:
    branches:
      - feature/cosme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch
        with:
          fetch-depth: 0
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: Apk
          path: |
            app/build/cosme/hola/hola.txt
          if-no-files-found: error
          retention-days: 1

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: Apk
          path: ./
      - name: Download Artifact
        run: |
          ls

      

